codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false

ignore:
  - "PhoenixTests/**/*"
  - "Reference/**/*"
